#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: set_turbo TURBO_STATUS"
    echo
    echo "Enable or disable Intel CPU turbo mode."
    echo "TURBO_STATUS should be 1 to enable turbo mode or 0 to disable it."
    exit 0
fi

if [[ "$1" == "--version" ]]; then
    echo "set_turbo 0.1"
    exit 0
fi


if [[ $# -gt 0 ]]
then
  # assert that the first argument is either 1 or 0
  if [[ $1 != "1" && $1 != "0" ]]
  then
    echo "Parameter must be 1 or 0"
    exit 1
  fi
  # check if the no_turbo file exists
  if [[ ! -f /sys/devices/system/cpu/intel_pstate/no_turbo ]]
  then
    echo "Turbo config file does not exist. This is likely because you are not using an Intel CPU."
    exit 1
  fi
  # write the value to the no_turbo file
	if [[ $1 == "1" ]]
  then
    echo 0 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo && \
    echo "Turbo mode enabled"
  elif [[ $1 == "0" ]]
  then
    echo 1 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo && \
    echo "Turbo mode disabled"
  fi
else
	echo "Missing turbo status parameter (1 or 0)"
  exit 1
fi
